### ISSUE TITLE
add composer.json for package

### ISSUE THREAD

**Issue by mycroft84** [barion/barion-web-php#15]
add composer.json for work composer require for install and update

**Comment by AdamDomafoldi** [comment]
A composer package would indeed be great!

**Comment by schalkt** [comment]
Please :)

- Put a file named composer.json at the root of your package's repository, containing this information:
```
{
    "name": "barion/barion-web-php",
    "description": "PHP libary for Barion gateway integration",
    "require": {
        "php": ">=7.3",
        "ext-curl": "*"
    }
}
```
- Add the composer.json to your git or other VCS repository and commit it.
- Log in or register on https://packagist.org/ site, then hit the submit button in the menu.
