### ISSUE TITLE
False error report for BillingAddressModel

### ISSUE THREAD

**Issue by impnet** [barion/barion-web-php#37]
Package falsely return error for missing string for BillingAddressModel::$Region

Even if property `Region` contains random string, error occured.

Property `Region` allow only string with length 2 char. That nonsence, region should be something like "Jihomoravský kraj", "Seatle", "Washington", et...

![obrazek](https://github.com/barion/barion-web-php/assets/46919973/3af69952-4ebb-469f-b979-b8b2411b9cb5)

**Comment by barion-vinczei** [comment]
Address regions must contain the country subdivision code (state or county) of the recipient address in ISO-3166-2 format, and must be exactly 2 characters to comply with the 3DSecure 2.2.0 EMVCo standard during card payments. This limitation is out of our jurisdiction.
However, proper validation and property documentation will be implemented to clarify this.
