### ISSUE TITLE
General errors - really bad application design

### ISSUE THREAD

**Issue by impnet** [barion/barion-web-php#38]
While using package there are several erros caused by developers of package (beginers mistakes).

1. Can not use classmap or filemap via composer. Classes of package contains nonsences "require/include" files. Loading another classes should do person who using package or this must be done via autoloader. If composer classmap used, then there will be error of duplicated interfaces and classes (one time loaded by composer and second time loaded via require/include file functions.
2. Defined global constants in file `library\common\Constants.php` are nonsence. This type of constant shoould not be used. This constant should be part of some class, like BarionClient or better there should be class like Endpoint etc...
3. Implemented library causing more than 70 errors in PHPStan due to missing autoloader and global constants. (this is only implementing part)
4. Package contains 16 erros which can not be ignored. Try to test package with PHPStan at level 5 (level 5 should be minimal level for any app). 
![obrazek](https://github.com/barion/barion-web-php/assets/46919973/8f18bb9d-a072-42c8-8dda-c34e1727e505)

This is really very bad design of package/app. Looks like programmed by beginers who doesn't know what they are doing.

**Comment by barion-vinczei** [comment]
Thank you very much for your input and suggestions throughout all issues.
We are indeed aware of the poor quality of the library and will soon do the necessary improvements to address every issue.
We will announce a next major release when everything is done.
